### ISSUE TITLE
是不是不支持m4a格式的音频了？

### ISSUE THREAD

**Issue by protosse** [potato04/AudioSpectrum#2]
我用这个podcast http://screencasts.b0.upaiyun.com/podcasts/teahour_episode_82.m4a 做了个测试，会崩在findMaxAmplitude这个函数。

**Comment by potato04** [comment]
你好，我试了一下并没有发现什么问题，动画能正常显示呢。测试环境是 Xcode 10.2.1 模拟器是 iPhone XS 12.2

**Comment by protosse** [comment]
> 你好，我试了一下并没有发现什么问题，动画能正常显示呢。测试环境是 Xcode 10.2.1 模拟器是 iPhone XS 12.2

你好，我试了下直接播放本地文件是没问题的，我是在线播放fetch AVAudioPCMBuffer的，但是这样得到的buffer的format.sampleRate和前面的不一样，前面的是48000，后面的是32000。
我再好好看下了。

**Comment by potato04** [comment]
如果方便的话提供你的代码我们来一起研究下

**Comment by protosse** [comment]
[AudioSpectrum02-final.zip](https://github.com/potato04/AudioSpectrum/files/3124546/AudioSpectrum02-final.zip)
大致改了下

**Comment by potato04** [comment]
抱歉，这么晚才回复。我下载代码并运行了，大概听了10多分钟吧，还是没能复现你所说的那个问题
不过，你在buffer的回调函数函数里面的这个语句可以删除：
```swift
buffer.frameLength = AVAudioFrameCount(2048)
```
因为你换了播放器之后，这里的设置肯定就没必要了。这里的buffer.frameLength都是4096，我暂时没找到这个播放器可以设置 tap 这个buffer大小的地方。

**Comment by protosse** [comment]
抱歉，我也现在才看到。没崩是因为findMaxAmplitude这个函数那里的代码我已经修改了
![image](https://user-images.githubusercontent.com/30048222/57499185-4a516f80-7311-11e9-86d3-77ab1903ec25.png)
怪我没先说，上面注释的代码是之前的。虽说崩溃原因是数组越界，但是我觉得这样并不是从根本解决。

**Comment by potato04** [comment]
你好，我看了下`findMaxAmplitude`修改之后的代码，你的目的是想避免 `endIndex < startIndex`
造成这个问题的原因呢，是因为参数`bandWidth`与实际的`bandWidth`不一致。
而`bandWidth = Float(buffer.format.sampleRate)  / Float(self.fftSize)`，也就是说`self.fftSize`错了
总之，我们只要确保 `RealtimeAnalyzer`对象中的`fftSize` 和 传给`analyse`的`buffer`的`frameLength`是一致的，就不会出问题。
以上就是根本解决的办法。
