### ISSUE TITLE
将代码拷贝到自己项目后，直接编译功能正常，打包后会卡死或闪退。

### ISSUE THREAD

**Issue by watermelonQAQ** [potato04/AudioSpectrum#6]
你好，我最近看到了你的代码，对我很有帮助，但有个很奇怪的问题，如标题所诉。我试了下直接将你的代码(AudioSpectrum01-final)打包后也是正常的，只有我的项目打包后会卡死或闪退。

在经过不断的注释打包后我发现是这一行代码有问题：  let amplitudes = strongSelf.fft(buffer)

但直接将代码编译到手机上功能就一切正常，打包后我看了日志打印也看不出有用的信息，日志如下：
![image](https://user-images.githubusercontent.com/35391315/158610854-abaa9877-2bf3-492b-8577-70128882da21.png)
请问对于这种现象有什么建议吗，谢谢

**Comment by potato04** [comment]
因为你的截图只有部分内容日志，我也看不出啥有效信息。
想想办法看能不能拿到更详细的日志（比如借助第三方工具），才能进行下一步分析。
